### ISSUE TITLE
bento is useless on Python2 code

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#184]
## Overview

I tried running bento on one of my Python2 projects. It reported 2 errors, which were just two tools failing to parse valid Python2 code.

## Current Behavior

~/D/crossword (master)> bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:00, 🍱
  r2c.flake8: |███████████████| 00:00, 🍱

crossword.py
  0:0  error   syntax error while parsing AST from file           r2c.bandit     error
723:48 error   SyntaxError: invalid syntax                        r2c.flake8     E999

⚠ 2 findings in 0.92 s
## Steps to Reproduce

Run bento on a project with Python2 code.

## Possible Solution

Possibly switch tools into a python2 mode, or just don't report invalid ASTs as "errors", wrap them into a metric.

## Additional Context
bento/0.5.0

**Comment by dlukeomalley** [comment]
Hi @ievans, thanks for filing this issue. Unfortunately we don't support Python 2. I've updated our README.md to clarify this, and am discussing with the team how to more gracefully fail on Python 2 files. Because this behavior is expected (it's not good though!) I'm labeling as `wont-fix`. I'll open a new issue for the graceful failure enhancement and echo back here.
