### ISSUE TITLE
Dlint shows only one line of code when displaying results that span multiple lines

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#279]
Dlint shows only one line of code when displaying results. Here’s an example on the Jinja project:
<img width="716" alt="Screen Shot 2020-02-18 at 5 20 55 PM" src="https://user-images.githubusercontent.com/302941/74792737-26916180-5273-11ea-9de4-27eb327c4cf0.png">

Dlint should display the whole block to which the result applies (starts with line 23):
```py
string_re = re.compile(
    r"('([^'\\]*(?:\\.[^'\\]*)*)'" r'|"([^"\\]*(?:\\.[^"\\]*)*)")', re.S
)
```

/cc @mschwager & @minusworld

**Comment by dlukeomalley** [comment]
@mschwager This might be a good ticket for you too before we get Dlint default enabled.

**Comment by mschwager** [comment]
Unfortunately this is a shortcoming of flake8, so implementing this behavior isn't easy. Since Dlint is built on flake8 it can only return data that flake8 allows it to. This includes: line number, column offset, message, and linter class (which includes error code, etc), but doesn't have a concept of beginning and end line number/column offset.

We certainly can block default enable on this functionality, but it may be a while before this behavior changes. I.e. it may require requesting changes upstream. So ultimately I believe this depends on how much we'd like to default enable Dlint vs. how much we care about multi line display.

**Comment by dlukeomalley** [comment]
Let's discuss this during today's sync and get @nbrahms thoughts. I'm still hopeful it's quick because we already support this type of output for other flake8-based tools 🤞
