### ISSUE TITLE
Make privacy link a hyperlink in terms of service

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#62]
![image](https://user-images.githubusercontent.com/605906/66504587-4a02ff00-ea7e-11e9-959b-81221465036d.png)

**Comment by deifactor** [comment]
As an iTerm2 user, I had no idea that the dashed underline we use in other places means that a link is clickable, so we'd want to make the link text the URL of the link anyway... at which point there's no point in making it a fancy link since cmd-clicking it will open it in a terminal (which is a feature most terminal emulators have).

**Comment by dlukeomalley** [comment]
Works for me. Closing out as `wont-fix`.
