### ISSUE TITLE
eslint errors on minimal-flask-react

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#66]
Running `bento check` on https://github.com/jwkvam/minimal-flask-react fails when parsing a valid jsx file:

> src/index.jsx
>   8:42 error   Parsing error: Unexpected token / r2c.eslint     error

![image](https://user-images.githubusercontent.com/605906/66507472-1d51e600-ea84-11e9-9b59-9e0fab347698.png)

**Comment by nbrahms** [comment]
Hi @dlukeomalley .

Thanks for the report. I'm able to reproduce this. However, I don't think this is a bug in bento. This is actually returned by eslint on this project.

In my reproduction, this was because the project did not properly install the `fsevents` node dependency. Can you validate that running:
```
npm list | grep UNMET
```
returns no results for you, on the project? If it does return items, that would imply you don't have the project itself installed correctly.

Our internal test for jsx parsing passes, so I'm going to remove the "bug" tag here for now.
