### ISSUE TITLE
eslint arrow-parens rule should be disabled

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#87]
Make sure you are running the latest version of Bento.

**Describe the bug**
Prettier omits parens whenever  possible
https://prettier.io/docs/en/options.html#arrow-function-parentheses

This creates an error with the current eslint configuration of Bento 

**Expected result**
no error

**Actual result**
error

**Additional context**
bento/0.1.0.post1

**Comment by dlukeomalley** [comment]
Thanks for filing this @daghan! We're including this rule because omitting the parens can contribute to correctness issues (see https://eslint.org/docs/rules/arrow-parens for a good write-up). For your specific project and the Prettier conflict I think the right next step is to run `bento disable arrow-parens`.

For the time being I'm going to close this issue, and we'll revisit in the next round of default config changes.
