### ISSUE TITLE
Document pre-commit hook usage

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#92]
We have some light documentation for `bento install-hook`, but for those unfamiliar with commit hooks the idea of having Bento block their commit is concerning. I'd like to document `git commit --no-verify`. From the user:

> if you want to push the commit hook workflow, I would recommend including some description of how to incorporate it into the workflow (like what you just sent me)
> 
> I think the people that would benefit the most from bento are people who aren't familiar with a lot of this sophisticated dev workflow stuff
> 
> And I think producing something similar for the commit hook approach -- like, a brief markdown guide about how to use commit hooks (or at least bento as a commit hook) and the benefits they offer your workflow, is even more valuable and lower hanging
> 
> I feel like there is a very long tail of developers (especially at smaller/less tech-prestigious companies) who (at least think they) get by okay without any of this fancy stuff, and wouldn't really know where to start

**Comment by arashd** [comment]
Agree strongly with this. Putting myself in a novice developer's shoes, if Bento isn't giving me an hook uninstall story, and I don't know much about hooks, it's borking a very important part of my workflow. I hate the tool at first impression because I'm locked in and have to go dig into git docs to get rid of it.

**Comment by arashd** [comment]
related to #43

**Comment by dlukeomalley** [comment]
Merged
